### ISSUE TITLE
New user is pointless

### ISSUE THREAD

**Issue by Skayzzz** [alexandrosmagos/instagram_commenter_ui#5]
Hey, could you remake the code so that when we log into another user, the comments and settings are reset ? Or at least the number of comments. I used the bot for a giveaway and now I want to use it for another giveaway, but I can't see the number of comments I sent on the 2nd post, I can only see the total number of comments because it can't be reset to 0 when I change the post link or lig into another user

**Comment by alexandrosmagos** [comment]
The login/register system was created purely so that the app can be publicly hosted or port forwarded for the user to remotely control the app, and not for multiple giveaways. I don't disagree that I'd be better, but it was just not made that way.

Also if you have the app running for more than one giveaway on one account, I can guarantee that your account will be blocked for posting for a few days, and if it continues after that block, will get a worse punishment. So if you want to run this for another giveaway, I suggest using a different Instagram account, from a different IP.

**Comment by Skayzzz** [comment]
I mean, if the giveaway ends and I now want to post comments on another giveaway (not the 2 at the same time), how can I reset the comments counter ?

**Comment by alexandrosmagos** [comment]
You can reset the counter by the button next to the counter.
![image](https://github.com/alexandrosmagos/instagram_commenter_ui/assets/12672076/848fe565-53ae-4285-a22e-c99f0c8d64c3)

Another option is to set the counter paramer to zero in the settings.json file in the setting folder.

The button was a few days ago when another person requested it. If you don't have the button, you need to update the files, so check the how to update section on the readme file.

**Comment by vekioschristos** [comment]
Thanks for the addition, pretty much appreciated!

**Comment by Skayzzz** [comment]
Oh yes, thank you ! I didn't see the button
